
#download project code
#install dependencies
#run the lint test and build scripts dans package.json

name: deploy and build
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Use NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm install
            - name: Run Tests
              run: npm ci
            - run: npm run build --if-present
            - run: npm run test
            - run: npm run lint