name: Listen for New Issues
on:
  issues:
    types: [opened]
jobs:
    issue-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Issue Title
              run: |  
                echo "New Issue Title: ${{ toJSON(github.event.issue.title) }}"
