
name: First Hello world sur GitHub
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"
      - name: Goodby World
        run: echo "Goodby, World!"

